//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoLoc.Application.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GeoLoc.Application.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UploadedFailed {
            get {
                return ResourceManager.GetString("UploadedFailed", resourceCulture);
            }
        }
        
        internal static string FilePickedWrongly {
            get {
                return ResourceManager.GetString("FilePickedWrongly", resourceCulture);
            }
        }
        
        internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        internal static string RecevingIsFailed {
            get {
                return ResourceManager.GetString("RecevingIsFailed", resourceCulture);
            }
        }
        
        internal static string FileIsNotFound {
            get {
                return ResourceManager.GetString("FileIsNotFound", resourceCulture);
            }
        }
        
        internal static string FilenameIsNotProvided {
            get {
                return ResourceManager.GetString("FilenameIsNotProvided", resourceCulture);
            }
        }
        
        internal static string DownloadingFileIsFailed {
            get {
                return ResourceManager.GetString("DownloadingFileIsFailed", resourceCulture);
            }
        }
        
        internal static string ReadingFileIsFailed {
            get {
                return ResourceManager.GetString("ReadingFileIsFailed", resourceCulture);
            }
        }
        
        internal static string ChartIsFailedToCreate {
            get {
                return ResourceManager.GetString("ChartIsFailedToCreate", resourceCulture);
            }
        }
        
        internal static string FailedToGetDataForMap {
            get {
                return ResourceManager.GetString("FailedToGetDataForMap", resourceCulture);
            }
        }
    }
}
